/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "washed-blue": {
          50: "var(--color-washed-blue-50)",
          100: "var(--color-washed-blue-100)",
          200: "var(--color-washed-blue-200)",
          300: "var(--color-washed-blue-300)",
          400: "var(--color-washed-blue-400)",
          500: "var(--color-washed-blue-500)",
          600: "var(--color-washed-blue-600)",
          700: "var(--color-washed-blue-700)",
          800: "var(--color-washed-blue-800)",
          900: "var(--color-washed-blue-900)",
        },
        "washed-purple": {
          50: "var(--color-washed-purple-50)",
          100: "var(--color-washed-purple-100)",
          200: "var(--color-washed-purple-200)",
          300: "var(--color-washed-purple-300)",
          400: "var(--color-washed-purple-400)",
          500: "var(--color-washed-purple-500)",
          600: "var(--color-washed-purple-600)",
          700: "var(--color-washed-purple-700)",
          800: "var(--color-washed-purple-800)",
          900: "var(--color-washed-purple-900)",
        },
        "primary-blue": {
          50: "var(--color-primary-blue-50)",
          100: "var(--color-primary-blue-100)",
          200: "var(--color-primary-blue-200)",
          300: "var(--color-primary-blue-300)",
          400: "var(--color-primary-blue-400)",
          500: "var(--color-primary-blue-500)",
          600: "var(--color-primary-blue-600)",
          700: "var(--color-primary-blue-700)",
          800: "var(--color-primary-blue-800)",
          900: "var(--color-primary-blue-900)",
        },
        "primary-purple": {
          50: "var(--color-primary-purple-50)",
          100: "var(--color-primary-purple-100)",
          200: "var(--color-primary-purple-200)",
          300: "var(--color-primary-purple-300)",
          400: "var(--color-primary-purple-400)",
          500: "var(--color-primary-purple-500)",
          600: "var(--color-primary-purple-600)",
          700: "var(--color-primary-purple-700)",
          800: "var(--color-primary-purple-800)",
          900: "var(--color-primary-purple-900)",
        },
        neutrals: {
          1: "var(--color-neutrals-1)",
          2: "var(--color-neutrals-2)",
          3: "var(--color-neutrals-3)",
          4: "var(--color-neutrals-4)",
          5: "var(--color-neutrals-5)",
          6: "var(--color-neutrals-6)",
          7: "var(--color-neutrals-7)",
          8: "var(--color-neutrals-8)",
          9: "var(--color-neutrals-9)",
          10: "var(--color-neutrals-10)",
          11: "var(--color-neutrals-11)",
          12: "var(--color-neutrals-12)",
          13: "var(--color-neutrals-13)",
        },
        brand: {
          washedpurple: "var(--color-brand-washedpurple)",
          washedblue: "var(--color-brand-washedblue)",
          primaryblue: "var(--color-brand-primaryblue)",
          primarypurple: "var(--color-brand-primarypurple)",
          dark: "var(--color-brand-dark)",
        },
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)", "Arial", "Helvetica", "sans-serif"],
        mono: ["var(--font-geist-mono)", "monospace"],
      },
    },
  },
  plugins: [],
};
